version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
      - FRONTEND_URL=${FRONTEND_URL:-*}
    networks:
      - perudo-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    expose:
      - "80"
    environment:
      - BACKEND_URL=${BACKEND_URL:-http://localhost:3000}
    depends_on:
      - backend
    networks:
      - perudo-network

networks:
  perudo-network:
    driver: bridge